url: https://ijada.it
baseurl: ""
google_analytics:

# Site settings
title: iJada IT
email: mhmd@ijada.it
description: "An awesome IT Team As A Service Startup"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mohammed Almusaddar
  pic: 7
  position: Cloud Engineer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/almusaddar

- name: Issam Fayad
  pic: 5
  position: WISP Engineer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/issamfayad


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: linkedin
    url:
  - title: github
    url: http://github.com

# Postal address (add as many lines as necessary)
address:
  - line: Mostafa Hafez St.
  - line: Gaza City, PS 00972

# Build settings
markdown: kramdown
permalink: pretty
